; Refresh your skin ... !Refresh * will refresh all
[Refresh]
Command=/!Refresh ConfigVariables

; Select Header Image to match PanelWidth (Height should be 60 px)
[HeaderImage]
Image=header300b.jpg

; Background window color under variable list
; Do not change Hex=0x ... modify last 6 digits for RRGGBB hex values
[BackgroundColor]
Hex=0xF4F4F4

; Font for text
[Font]
FontFace=Segoe UI

; Font size
; Recommend between 8~14 dependent on Font
[FontSize]
FontHeight=14

; Name displayed in the Taskbar area
[TaskbarTitle]
Title=Skin Configure

; Window width; should match HeaderImage width
[PanelWidth]
Width=300

; Window height
[PanelHeight]
Height=400

; Estimated height of description area; will vary with Font style and size
[DescriptionLines]
DescriptLines=2
